"""
Location mapping for FindMyCure Italia.
This module provides functionality to map Italian cities to their respective regions,
enabling more intuitive search results based on location references.
"""

# Map of Italian cities to their regions (including smaller municipalities)
# Format: 'city_name': 'region_name'
CITY_TO_REGION_MAP = {
    # Lombardia
    'milano': 'Lombardia',
    'bergamo': 'Lombardia',
    'brescia': 'Lombardia',
    'como': 'Lombardia',
    'cremona': 'Lombardia',
    'lecco': 'Lombardia',
    'lodi': 'Lombardia',
    'mantova': 'Lombardia',
    'monza': 'Lombardia',
    'pavia': 'Lombardia',
    'sondrio': 'Lombardia',
    'varese': 'Lombardia',
    'busto arsizio': 'Lombardia',
    'cinisello balsamo': 'Lombardia',
    'legnano': 'Lombardia',
    'rho': 'Lombardia',
    'cologno monzese': 'Lombardia',
    'paderno dugnano': 'Lombardia',
    'seregno': 'Lombardia',
    'cesano maderno': 'Lombardia',
    'segrate': 'Lombardia',
    
    # Lazio
    'roma': 'Lazio',
    'frosinone': 'Lazio',
    'latina': 'Lazio',
    'rieti': 'Lazio',
    'viterbo': 'Lazio',
    'guidonia': 'Lazio',
    'fiumicino': 'Lazio',
    'civitavecchia': 'Lazio',
    'velletri': 'Lazio',
    'anzio': 'Lazio',
    'nettuno': 'Lazio',
    'formia': 'Lazio',
    'ostia': 'Lazio',
    'cerveteri': 'Lazio',
    
    # Campania
    'napoli': 'Campania',
    'avellino': 'Campania',
    'benevento': 'Campania',
    'caserta': 'Campania',
    'salerno': 'Campania',
    'acerra': 'Campania',
    'afragola': 'Campania', 
    'agropoli': 'Campania',
    'amalfi': 'Campania',
    'angri': 'Campania',
    'ariano irpino': 'Campania',
    'arzano': 'Campania',
    'atripalda': 'Campania',
    'aversa': 'Campania',
    'bacoli': 'Campania',
    'battipaglia': 'Campania',
    'capua': 'Campania',
    'castellammare di stabia': 'Campania',
    'cava de tirreni': 'Campania',
    'ercolano': 'Campania',
    'giugliano in campania': 'Campania',
    'ischia': 'Campania',
    'marcianise': 'Campania',
    'marano di napoli': 'Campania',
    'mercato san severino': 'Campania',
    'nocera inferiore': 'Campania',
    'nola': 'Campania',
    'pagani': 'Campania',
    'piano di sorrento': 'Campania',
    'pompei': 'Campania',
    'portici': 'Campania',
    'positano': 'Campania',
    'pozzuoli': 'Campania',
    'ravello': 'Campania',
    'sant\'agnello': 'Campania',
    'sant\'anastasia': 'Campania',
    'scafati': 'Campania',
    'sorrento': 'Campania',
    'torre annunziata': 'Campania',
    'torre del greco': 'Campania',
    'vico equense': 'Campania',
    'volla': 'Campania',
    
    # Sicilia
    'palermo': 'Sicilia',
    'agrigento': 'Sicilia',
    'caltanissetta': 'Sicilia',
    'catania': 'Sicilia',
    'enna': 'Sicilia',
    'messina': 'Sicilia',
    'ragusa': 'Sicilia',
    'siracusa': 'Sicilia',
    'trapani': 'Sicilia',
    
    # Veneto
    'venezia': 'Veneto',
    'belluno': 'Veneto',
    'padova': 'Veneto',
    'rovigo': 'Veneto',
    'treviso': 'Veneto',
    'verona': 'Veneto',
    'vicenza': 'Veneto',
    'abano terme': 'Veneto',
    'adria': 'Veneto',
    'albignasego': 'Veneto',
    'arzignano': 'Veneto',
    'asolo': 'Veneto',
    'bassano del grappa': 'Veneto',
    'caorle': 'Veneto',
    'castelfranco veneto': 'Veneto',
    'chioggia': 'Veneto',
    'cittadella': 'Veneto',
    'conegliano': 'Veneto',
    'cortina d\'ampezzo': 'Veneto',
    'dolo': 'Veneto',
    'este': 'Veneto',
    'feltre': 'Veneto',
    'jesolo': 'Veneto',
    'legnago': 'Veneto',
    'mestre': 'Veneto',
    'mirano': 'Veneto',
    'montebelluna': 'Veneto',
    'monselice': 'Veneto',
    'negrar': 'Veneto',
    'noale': 'Veneto',
    'oderzo': 'Veneto',
    'peschiera del garda': 'Veneto',
    'piove di sacco': 'Veneto',
    'portogruaro': 'Veneto',
    'san donà di piave': 'Veneto',
    'schio': 'Veneto',
    'spinea': 'Veneto',
    'thiene': 'Veneto',
    'villafranca di verona': 'Veneto',
    'vittorio veneto': 'Veneto',
    
    # Piemonte
    'torino': 'Piemonte',
    'alessandria': 'Piemonte',
    'asti': 'Piemonte',
    'biella': 'Piemonte',
    'cuneo': 'Piemonte',
    'novara': 'Piemonte',
    'verbania': 'Piemonte',
    'vercelli': 'Piemonte',
    
    # Emilia-Romagna
    'bologna': 'Emilia-Romagna',
    'ferrara': 'Emilia-Romagna',
    'forlì': 'Emilia-Romagna',
    'cesena': 'Emilia-Romagna',
    'modena': 'Emilia-Romagna',
    'parma': 'Emilia-Romagna',
    'piacenza': 'Emilia-Romagna',
    'ravenna': 'Emilia-Romagna',
    'reggio emilia': 'Emilia-Romagna',
    'rimini': 'Emilia-Romagna',
    
    # Puglia
    'bari': 'Puglia',
    'brindisi': 'Puglia',
    'foggia': 'Puglia',
    'lecce': 'Puglia',
    'taranto': 'Puglia',
    'altamura': 'Puglia',
    'andria': 'Puglia',
    'barletta': 'Puglia',
    'bisceglie': 'Puglia',
    'bitonto': 'Puglia',
    'canosa di puglia': 'Puglia',
    'cerignola': 'Puglia',
    'conversano': 'Puglia',
    'corato': 'Puglia',
    'fasano': 'Puglia',
    'francavilla fontana': 'Puglia',
    'gallipoli': 'Puglia',
    'galatina': 'Puglia',
    'gioia del colle': 'Puglia',
    'giovinazzo': 'Puglia',
    'gravina in puglia': 'Puglia',
    'grottaglie': 'Puglia',
    'lucera': 'Puglia',
    'manduria': 'Puglia',
    'manfredonia': 'Puglia',
    'martina franca': 'Puglia',
    'massafra': 'Puglia',
    'mesagne': 'Puglia',
    'molfetta': 'Puglia',
    'monopoli': 'Puglia',
    'nardò': 'Puglia',
    'ostuni': 'Puglia',
    'otranto': 'Puglia',
    'polignano a mare': 'Puglia',
    'putignano': 'Puglia',
    'ruvo di puglia': 'Puglia',
    'san giovanni rotondo': 'Puglia',
    'san severo': 'Puglia',
    'terlizzi': 'Puglia',
    'trani': 'Puglia',
    'tricase': 'Puglia',
    'vieste': 'Puglia',
    
    # Toscana
    'firenze': 'Toscana',
    'arezzo': 'Toscana',
    'grosseto': 'Toscana',
    'livorno': 'Toscana',
    'lucca': 'Toscana',
    'massa': 'Toscana',
    'carrara': 'Toscana',
    'pisa': 'Toscana',
    'pistoia': 'Toscana',
    'prato': 'Toscana',
    'siena': 'Toscana',
    'bagno a ripoli': 'Toscana',
    'calenzano': 'Toscana',
    'campi bisenzio': 'Toscana',
    'capannori': 'Toscana',
    'cascina': 'Toscana',
    'castagneto carducci': 'Toscana',
    'castelfiorentino': 'Toscana',
    'castiglione della pescaia': 'Toscana',
    'cecina': 'Toscana',
    'certaldo': 'Toscana',
    'chianciano terme': 'Toscana',
    'colle di val d\'elsa': 'Toscana',
    'cortona': 'Toscana',
    'empoli': 'Toscana',
    'figline valdarno': 'Toscana',
    'follonica': 'Toscana',
    'forte dei marmi': 'Toscana',
    'fucecchio': 'Toscana',
    'montecatini terme': 'Toscana',
    'montepulciano': 'Toscana',
    'pescia': 'Toscana',
    'pietrasanta': 'Toscana',
    'piombino': 'Toscana',
    'poggibonsi': 'Toscana',
    'pontassieve': 'Toscana',
    'pontedera': 'Toscana',
    'portoferraio': 'Toscana',
    'rosignano marittimo': 'Toscana',
    'san gimignano': 'Toscana',
    'san miniato': 'Toscana',
    'scandicci': 'Toscana',
    'sesto fiorentino': 'Toscana',
    'viareggio': 'Toscana',
    'volterra': 'Toscana',
    
    # Calabria
    'catanzaro': 'Calabria',
    'cosenza': 'Calabria',
    'crotone': 'Calabria',
    'reggio calabria': 'Calabria',
    'vibo valentia': 'Calabria',
    'acri': 'Calabria',
    'amantea': 'Calabria',
    'bagnara calabra': 'Calabria',
    'belvedere marittimo': 'Calabria',
    'bisignano': 'Calabria',
    'bovalino': 'Calabria',
    'castrovillari': 'Calabria',
    'cetraro': 'Calabria',
    'cirò marina': 'Calabria',
    'cittanova': 'Calabria',
    'corigliano calabro': 'Calabria',
    'diamante': 'Calabria',
    'gioia tauro': 'Calabria',
    'isola di capo rizzuto': 'Calabria',
    'lamezia terme': 'Calabria',
    'locri': 'Calabria',
    'melito di porto salvo': 'Calabria',
    'montalto uffugo': 'Calabria',
    'palmi': 'Calabria',
    'paola': 'Calabria',
    'pizzo': 'Calabria',
    'praia a mare': 'Calabria',
    'rende': 'Calabria',
    'rossano': 'Calabria',
    'rosarno': 'Calabria',
    'san giovanni in fiore': 'Calabria',
    'scalea': 'Calabria',
    'siderno': 'Calabria',
    'soverato': 'Calabria',
    'taurianova': 'Calabria',
    'tropea': 'Calabria',
    'villa san giovanni': 'Calabria',
    
    # Sardegna
    'cagliari': 'Sardegna',
    'carbonia': 'Sardegna',
    'nuoro': 'Sardegna',
    'olbia': 'Sardegna',
    'oristano': 'Sardegna',
    'sassari': 'Sardegna',
    'alghero': 'Sardegna',
    'arzachena': 'Sardegna',
    'assemini': 'Sardegna',
    'bosa': 'Sardegna',
    'budoni': 'Sardegna',
    'capoterra': 'Sardegna',
    'carloforte': 'Sardegna',
    'castelsardo': 'Sardegna',
    'dorgali': 'Sardegna',
    'guspini': 'Sardegna',
    'iglesias': 'Sardegna',
    'la maddalena': 'Sardegna',
    'macomer': 'Sardegna',
    'monserrato': 'Sardegna',
    'muravera': 'Sardegna',
    'palau': 'Sardegna',
    'porto torres': 'Sardegna',
    'pula': 'Sardegna',
    'quartu sant\'elena': 'Sardegna',
    'quartucciu': 'Sardegna',
    'san teodoro': 'Sardegna',
    'sant\'antioco': 'Sardegna',
    'santa teresa gallura': 'Sardegna',
    'selargius': 'Sardegna',
    'siniscola': 'Sardegna',
    'sinnai': 'Sardegna',
    'sorso': 'Sardegna',
    'tempio pausania': 'Sardegna',
    'tertenia': 'Sardegna',
    'tortolì': 'Sardegna',
    'villacidro': 'Sardegna',
    'villasimius': 'Sardegna',
    
    # Liguria
    'genova': 'Liguria',
    'imperia': 'Liguria',
    'la spezia': 'Liguria',
    'savona': 'Liguria',
    'finale ligure': 'Liguria',
    'alassio': 'Liguria',
    'albenga': 'Liguria',
    'albisola': 'Liguria',
    'arenzano': 'Liguria',
    'bordighera': 'Liguria',
    'camogli': 'Liguria',
    'chiavari': 'Liguria',
    'lavagna': 'Liguria',
    'loano': 'Liguria',
    'pietra ligure': 'Liguria',
    'rapallo': 'Liguria',
    'recco': 'Liguria',
    'sanremo': 'Liguria',
    'santa margherita ligure': 'Liguria',
    'sestri levante': 'Liguria',
    'taggia': 'Liguria',
    'ventimiglia': 'Liguria',
    'varazze': 'Liguria',
    
    # Marche
    'ancona': 'Marche',
    'ascoli piceno': 'Marche',
    'fermo': 'Marche',
    'macerata': 'Marche',
    'pesaro': 'Marche',
    'urbino': 'Marche',
    'camerino': 'Marche',
    'castelfidardo': 'Marche',
    'civitanova marche': 'Marche',
    'cupra marittima': 'Marche',
    'fabriano': 'Marche',
    'falconara marittima': 'Marche',
    'fano': 'Marche',
    'grottammare': 'Marche',
    'jesi': 'Marche',
    'loreto': 'Marche',
    'montegranaro': 'Marche',
    'osimo': 'Marche',
    'porto recanati': 'Marche',
    'porto san giorgio': 'Marche',
    'porto sant\'elpidio': 'Marche',
    'recanati': 'Marche',
    'san benedetto del tronto': 'Marche',
    'senigallia': 'Marche',
    'tolentino': 'Marche',
    
    # Abruzzo
    'l\'aquila': 'Abruzzo',
    'laquila': 'Abruzzo',
    'chieti': 'Abruzzo',
    'pescara': 'Abruzzo',
    'teramo': 'Abruzzo',
    'alba adriatica': 'Abruzzo',
    'atri': 'Abruzzo',
    'avezzano': 'Abruzzo',
    'città sant\'angelo': 'Abruzzo',
    'francavilla al mare': 'Abruzzo',
    'giulianova': 'Abruzzo',
    'guardiagrele': 'Abruzzo',
    'lanciano': 'Abruzzo',
    'martinsicuro': 'Abruzzo',
    'montesilvano': 'Abruzzo',
    'ortona': 'Abruzzo',
    'penne': 'Abruzzo',
    'pineto': 'Abruzzo',
    'roseto degli abruzzi': 'Abruzzo',
    'san salvo': 'Abruzzo',
    'silvi': 'Abruzzo',
    'spoltore': 'Abruzzo',
    'sulmona': 'Abruzzo',
    'tortoreto': 'Abruzzo',
    'vasto': 'Abruzzo',
    
    # Friuli-Venezia Giulia
    'trieste': 'Friuli-Venezia Giulia',
    'gorizia': 'Friuli-Venezia Giulia',
    'pordenone': 'Friuli-Venezia Giulia',
    'udine': 'Friuli-Venezia Giulia',
    'friuli': 'Friuli-Venezia Giulia',
    'friuli venezia giulia': 'Friuli-Venezia Giulia',
    'venezia giulia': 'Friuli-Venezia Giulia',
    'friuli-venezia giulia': 'Friuli-Venezia Giulia',
    'aquileia': 'Friuli-Venezia Giulia',
    'aviano': 'Friuli-Venezia Giulia',
    'cervignano del friuli': 'Friuli-Venezia Giulia',
    'cividale del friuli': 'Friuli-Venezia Giulia',
    'codroipo': 'Friuli-Venezia Giulia',
    'cordenons': 'Friuli-Venezia Giulia',
    'gemona del friuli': 'Friuli-Venezia Giulia',
    'gradisca d\'isonzo': 'Friuli-Venezia Giulia',
    'grado': 'Friuli-Venezia Giulia',
    'latisana': 'Friuli-Venezia Giulia',
    'lignano sabbiadoro': 'Friuli-Venezia Giulia',
    'maniago': 'Friuli-Venezia Giulia',
    'monfalcone': 'Friuli-Venezia Giulia',
    'muggia': 'Friuli-Venezia Giulia',
    'palmanova': 'Friuli-Venezia Giulia',
    'sacile': 'Friuli-Venezia Giulia',
    'san daniele del friuli': 'Friuli-Venezia Giulia',
    'san vito al tagliamento': 'Friuli-Venezia Giulia',
    'spilimbergo': 'Friuli-Venezia Giulia',
    'tarvisio': 'Friuli-Venezia Giulia',
    'tolmezzo': 'Friuli-Venezia Giulia',
    
    # Trentino-Alto Adige
    'trento': 'Trentino',
    'bolzano': 'Trentino',
    'alto adige': 'Trentino',
    'trentino alto adige': 'Trentino',
    'trentino-alto adige': 'Trentino',
    'ala': 'Trentino',
    'andalo': 'Trentino',
    'arco': 'Trentino',
    'bressanone': 'Trentino',
    'brunico': 'Trentino',
    'campo tures': 'Trentino',
    'canazei': 'Trentino',
    'cavalese': 'Trentino',
    'cles': 'Trentino',
    'dobbiaco': 'Trentino',
    'folgaria': 'Trentino',
    'folgarida': 'Trentino',
    'fondo': 'Trentino',
    'lana': 'Trentino',
    'lavis': 'Trentino',
    'levico terme': 'Trentino',
    'madonna di campiglio': 'Trentino',
    'malè': 'Trentino',
    'male': 'Trentino',
    'merano': 'Trentino',
    'mezzana': 'Trentino',
    'moena': 'Trentino',
    'molveno': 'Trentino',
    'ortisei': 'Trentino',
    'pergine valsugana': 'Trentino',
    'pinzolo': 'Trentino',
    'predazzo': 'Trentino',
    'riva del garda': 'Trentino',
    'rovereto': 'Trentino',
    'san martino di castrozza': 'Trentino',
    'selva di val gardena': 'Trentino',
    'siror': 'Trentino',
    'spiazzo': 'Trentino',
    'storo': 'Trentino',
    'tione di trento': 'Trentino',
    'tirolo': 'Trentino',
    'vipiteno': 'Trentino',
    
    # Umbria
    'perugia': 'Umbria',
    'terni': 'Umbria',
    'assisi': 'Umbria',
    'bastia umbra': 'Umbria',
    'bettona': 'Umbria',
    'bevagna': 'Umbria',
    'cascia': 'Umbria',
    'castiglione del lago': 'Umbria',
    'città di castello': 'Umbria',
    'citta di castello': 'Umbria',
    'corciano': 'Umbria',
    'deruta': 'Umbria',
    'foligno': 'Umbria',
    'gualdo tadino': 'Umbria',
    'gubbio': 'Umbria',
    'marsciano': 'Umbria',
    'montefalco': 'Umbria',
    'narni': 'Umbria',
    'norcia': 'Umbria',
    'orvieto': 'Umbria',
    'passignano sul trasimeno': 'Umbria',
    'spello': 'Umbria',
    'spoleto': 'Umbria',
    'todi': 'Umbria',
    'umbertide': 'Umbria',
    
    # Basilicata
    'potenza': 'Basilicata',
    'matera': 'Basilicata',
    'bernalda': 'Basilicata',
    'ferrandina': 'Basilicata',
    'garaguso': 'Basilicata',
    'grassano': 'Basilicata',
    'lagonegro': 'Basilicata',
    'latronico': 'Basilicata',
    'laurenzana': 'Basilicata',
    'lavello': 'Basilicata',
    'maratea': 'Basilicata',
    'melfi': 'Basilicata',
    'metaponto': 'Basilicata',
    'montescaglioso': 'Basilicata',
    'nova siri': 'Basilicata',
    'picerno': 'Basilicata',
    'pisticci': 'Basilicata',
    'policoro': 'Basilicata',
    'rionero in vulture': 'Basilicata',
    'rivello': 'Basilicata',
    'scanzano jonico': 'Basilicata',
    'senise': 'Basilicata',
    'stigliano': 'Basilicata',
    'tricarico': 'Basilicata',
    'venosa': 'Basilicata',
    
    # Molise
    'campobasso': 'Molise',
    'isernia': 'Molise',
    'agnone': 'Molise',
    'baranello': 'Molise',
    'bojano': 'Molise',
    'campomarino': 'Molise',
    'cantalupo nel sannio': 'Molise',
    'carpinone': 'Molise',
    'casacalenda': 'Molise',
    'castelmauro': 'Molise',
    'cerro al volturno': 'Molise',
    'frosolone': 'Molise',
    'guglionesi': 'Molise',
    'larino': 'Molise',
    'macchia d\'isernia': 'Molise',
    'montenero di bisaccia': 'Molise',
    'riccia': 'Molise',
    'santa croce di magliano': 'Molise',
    'termoli': 'Molise',
    'trivento': 'Molise',
    'ururi': 'Molise',
    'venafro': 'Molise',
    
    # Valle d'Aosta
    'aosta': 'Valle d Aosta',
    'valle d\'aosta': 'Valle d Aosta',
    'val d\'aosta': 'Valle d Aosta',
    'valle d aosta': 'Valle d Aosta',
    'val d aosta': 'Valle d Aosta',
    'antey-saint-andré': 'Valle d Aosta',
    'antey saint andre': 'Valle d Aosta',
    'arvier': 'Valle d Aosta',
    'ayas': 'Valle d Aosta',
    'breuil-cervinia': 'Valle d Aosta',
    'cervinia': 'Valle d Aosta',
    'chamois': 'Valle d Aosta',
    'champoluc': 'Valle d Aosta',
    'châtillon': 'Valle d Aosta',
    'chatillon': 'Valle d Aosta',
    'cogne': 'Valle d Aosta',
    'courmayeur': 'Valle d Aosta',
    'donnas': 'Valle d Aosta',
    'étroubles': 'Valle d Aosta',
    'etroubles': 'Valle d Aosta',
    'fénis': 'Valle d Aosta',
    'fenis': 'Valle d Aosta',
    'gressoney-la-trinité': 'Valle d Aosta',
    'gressoney la trinite': 'Valle d Aosta',
    'gressoney-saint-jean': 'Valle d Aosta',
    'gressoney saint jean': 'Valle d Aosta',
    'la salle': 'Valle d Aosta',
    'la thuile': 'Valle d Aosta',
    'morgex': 'Valle d Aosta',
    'nus': 'Valle d Aosta',
    'pila': 'Valle d Aosta',
    'pont-saint-martin': 'Valle d Aosta',
    'pont saint martin': 'Valle d Aosta',
    'pré-saint-didier': 'Valle d Aosta',
    'pre saint didier': 'Valle d Aosta',
    'quart': 'Valle d Aosta',
    'saint-pierre': 'Valle d Aosta',
    'saint pierre': 'Valle d Aosta',
    'saint-vincent': 'Valle d Aosta',
    'saint vincent': 'Valle d Aosta',
    'sarre': 'Valle d Aosta',
    'valgrisenche': 'Valle d Aosta',
    'valpelline': 'Valle d Aosta',
    'valtournenche': 'Valle d Aosta',
    'verres': 'Valle d Aosta',
}

def detect_location_in_query(query):
    """
    Detect city/location references in a query and map them to regions.
    
    Args:
        query (str): The user's search query text
        
    Returns:
        tuple: (cleaned_query, region_name)
            - cleaned_query: query with location references removed
            - region_name: detected region or None if no location found
    """
    if not query:
        return query, None
    
    # Convert query to lowercase
    query_lower = query.lower()
    
    # Check for direct city matches
    detected_region = None
    detected_city = None
    
    # Check each city in our map
    for city, region in CITY_TO_REGION_MAP.items():
        # Check for exact word match (with word boundaries)
        if f" {city} " in f" {query_lower} " or query_lower.startswith(f"{city} ") or query_lower.endswith(f" {city}") or query_lower == city:
            detected_city = city
            detected_region = region
            break
    
    # If a city was found, remove it from the query
    cleaned_query = query
    if detected_city:
        # Remove the city from the query using regex-like replacements
        cleaned_query = query_lower.replace(detected_city, "").strip()
        
        # Clean up any double spaces
        while "  " in cleaned_query:
            cleaned_query = cleaned_query.replace("  ", " ")
            
        # If the query equals the city name (or becomes empty after removal),
        # we should treat this as a region-only search with no additional text filter
        if not cleaned_query or cleaned_query.isspace():
            # Log this special case
            print(f"Query '{query}' was fully consumed by location '{detected_city}', setting cleaned_query to empty")
            cleaned_query = ""
    
    return cleaned_query, detected_region